// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int"; DO NOT EDIT.

package codegen

// init register error codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	register(ErrEncrypt, 401, "Error occurred while encrypting the user password")
}
